### ISSUE TITLE
<USER STORY> Site Owner Navigation Bar

### ISSUE THREAD

**Issue by Libbu** [Libbu/CyberPixels#1]
As a **site-owner** I want **users to be able to navigate my site** so that **they can find information**

### Acceptance Criteria

- Information on website is nicely organised. 
- A site navigation area is displayed. 
- Links in navigation links to relevant area. 

### Tasks

- [ ] Develop a navbar. 
- [ ] Develop site structure. 
- [ ] Link  pages via navbar. 
- [ ] Style information clearly with css.
