### ISSUE TITLE
<USER STORY> Site User - Images

### ISSUE THREAD

**Issue by Libbu** [Libbu/CyberPixels#2]
As a **user** I would like **to see high quality pictures of destinations** so I can decide if I want to go there. 

### Acceptance Criteria

- Acceptance Criteria 1: Relevant pictures to content.
- Acceptance Criteria 2: Pictures are high quality. 
- Acceptance Criteria 3: Relevant picture captions. 
- Acceptance Criteria 4: Pictures display on site

### Tasks

- [ ] Find high quality relevant pictures of destinations.
- [ ] Caption pictures with relevant text. 
- [ ] Test to ensure picture appear on the site. 
- [ ] Add image assets to website code. 
- [ ] Style image assets with css.
