### ISSUE TITLE
<USER STORY>  Site Owner sign up page

### ISSUE THREAD

**Issue by Libbu** [Libbu/CyberPixels#3]
As a **site owner** I want **users to be able to enquire about the tour** so that I can **convert them to customers**

### Acceptance Criteria

- Acceptance Criteria 1: Sign up page is on the website. 
- Acceptance Criteria 2: Information collected can easily be submitted. 
- Acceptance Criteria 3: User feedback of information being sent. 

### Tasks

- [ ] Develop form. 
- [ ] Style form with css. 
- [ ] Create submit button. 
- [ ] Style button for user feedback. 
- [ ] Code required fields.
