### ISSUE TITLE
<USER STORY> Site owner homepage

### ISSUE THREAD

**Issue by Libbu** [Libbu/CyberPixels#6]
As a **site owner** I **want a meaningful homepage** so that **users know what is available on the site.** 

### Acceptance Criteria

- Acceptance Criteria 1: Homepage exists. 
- Acceptance Criteria 2: Clearly display purpose of website. 
- Acceptance Criteria 3: All information is relevant. 
- Acceptance Criteria 4: The styling of the homepage is appropriate to the business. 

### Tasks

- [ ] Create a homepage. 
- [ ] Style homepage appropriately to the business. 
- [ ] Include relevant summary information. 
- [ ] Style the homepage so that the purpose is clear.
