### ISSUE TITLE
<USER STORY> User seeing social media links

### ISSUE THREAD

**Issue by Libbu** [Libbu/CyberPixels#9]
As a **user** I want  **to see social media links** so that I can **follow them on different platforms.** 

### Acceptance Criteria

- Acceptance Criteria 1: Social media links are available. 
- Acceptance Criteria 2: Links to social media work and open in a separate tabs. 
- Acceptance Criteria 3: Social media links are clearly displayed across the website. 

### Tasks

- [ ] Link icons to social media platforms. 
- [ ] Test the links to ensure they work as intended. 
- [ ]Develop a clear area for links to be displayed.
